### ISSUE TITLE
Bug at generate marks

### ISSUE THREAD

**Issue by jyC23333** [roboflow/multimodal-maestro#14]
### Search before asking

- [X] I have searched the Multimodal Maestro [issues](https://github.com/roboflow/multimodal-maestro/issues) and found no similar bug report.

### Bug

Traceback (most recent call last):
  File "/data/megvii/projects/Qwen-VL/scripts/test_maestro.py", line 7, in <module>
    marks = generator.generate(image=image)
  File "/data/Anaconda/anaconda3/envs/autogpt/lib/python3.10/site-packages/maestro/markers/sam.py", line 44, in generate
    return masks_to_marks(masks=masks)
  File "/data/Anaconda/anaconda3/envs/autogpt/lib/python3.10/site-packages/maestro/postprocessing/mask.py", line 187, in masks_to_marks
    return sv.Detections(
  File "<string>", line 8, in __init__
  File "/data/Anaconda/anaconda3/envs/autogpt/lib/python3.10/site-packages/supervision/detection/core.py", line 89, in __post_init__
    _validate_mask(mask=self.mask, n=n)
  File "/data/Anaconda/anaconda3/envs/autogpt/lib/python3.10/site-packages/supervision/detection/core.py", line 29, in _validate_mask
    raise ValueError("mask must be 3d np.ndarray with (n, H, W) shape")
ValueError: mask must be 3d np.ndarray with (n, H, W) shape

### Environment

Ubuntu 20.04
python=3.10.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @jyC23333! 👋🏻 Could you share the code you run and image you used? Basically something more so I can understand better what happens?

**Comment by jyC23333** [comment]
Hi，@SkalskiP ，my code shows below:
```python
import cv2
import maestro

image = cv2.imread('./鲫鱼.png')

generator = maestro.SegmentAnythingMarkGenerator(device='cuda')
marks = generator.generate(image=image)
marks = maestro.refine_marks(marks=marks)

mark_visualizer = maestro.MarkVisualizer()
marked_image = mark_visualizer.visualize(image=image, marks=marks)
```

something wrong at this line:
```python
marks = generator.generate(image=image)
```

original image:
![鲫鱼](https://github.com/roboflow/multimodal-maestro/assets/110331827/66d709d7-e5cf-4294-98ce-72c484a43731)

**Comment by SkalskiP** [comment]
Thanks @jyC23333. I'll get back to you!

**Comment by jyC23333** [comment]
@SkalskiP Hi，the bug still exists with the latest version.
![image](https://github.com/roboflow/multimodal-maestro/assets/110331827/e5d7e24f-81db-485c-a232-c2d0137509c3)

This is my cuda info:
![image](https://github.com/roboflow/multimodal-maestro/assets/110331827/48aeb4a8-dfec-4b44-94a9-472a6ade1332)

And I'm using torch 2.1.0:
![image](https://github.com/roboflow/multimodal-maestro/assets/110331827/e02fb66b-792d-42db-8352-79502e0d3839)

**Comment by SkalskiP** [comment]
Hi @jyC23333, the bug doesn't exist in the Colab I sent you, so it must be environment-dependent. What version of `transformers` and `supervision` you have?

**Comment by jyC23333** [comment]
@SkalskiP Hi，the dependent info is:
![image](https://github.com/roboflow/multimodal-maestro/assets/110331827/10c7d34e-b95a-4e28-b851-2a135154cb3a)
![image](https://github.com/roboflow/multimodal-maestro/assets/110331827/cde75759-4cf7-492c-9f75-27da5a52b8dd)

**Comment by hvaria** [comment]
To address the bug, add debug logs around self.pipeline in generate to check data shapes and integrity. Monitor GPU usage to ensure no memory overflow—silent issues may not trigger clear error messages

**Comment by SkalskiP** [comment]
I'm very sorry, but I'm extremely busy. I'll try to look at it as soon as possible.
