### ISSUE TITLE
Improve segmentation step to get single label and single marker for each object

### ISSUE THREAD

**Issue by ramsrigouthamg** [roboflow/multimodal-maestro#16]
### Search before asking

- [X] I have searched the Multimodal Maestro [issues](https://github.com/roboflow/multimodal-maestro/issues) and found no similar feature requests.

### Description

I am trying to achieve segmentation of objects such that each object has only one label and clear segmentation boundary defined.
At the moment in the post-processing refiner step of the tutorial (Colab) notebook in the repo, the hard-coded 0.02 value isn’t perfect for most images and misses correct segmentation clusters. So misses most individual objects or they are clustered with the background. 

The refiner function does 4 different tasks at once (hole filling, minimum area , max …) Good to isolate or please suggest a better way to isolate individual objects and their segmentation pixels perfectly.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @ramsrigouthamg! 👋🏻 Thank you for your interest in our project. You can already run the following functions independently:
- [hole filling and islands removal](https://github.com/roboflow/multimodal-maestro/blob/80f3294cb82c0812ab3da1a69acf4d3a31d3f089/maestro/postprocessing/mask.py#L126)
- [size filtering](https://github.com/roboflow/multimodal-maestro/blob/80f3294cb82c0812ab3da1a69acf4d3a31d3f089/maestro/postprocessing/mask.py#L87)
- [non-max impression](https://github.com/roboflow/multimodal-maestro/blob/80f3294cb82c0812ab3da1a69acf4d3a31d3f089/maestro/postprocessing/mask.py#L50)

**Comment by ramsrigouthamg** [comment]
Thanks @SkalskiP 
Is there support/potential to include support for https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once in this library?
Basically, I was trying to get better segmentation masks instead of traditional SAM and merging which is erroneous.

**Comment by SkalskiP** [comment]
I`d love to. [Set-of-Mark Prompting Unleashes Extraordinary Visual Grounding in GPT-4V](https://arxiv.org/abs/2310.11441) paper used SEEM as well.

But I want Maestro to me easy to install. I don't want to force people to go through [this](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/v1.0/assets/readmes/INSTALL.md) installation process when installing Maestro. So, if we would integrate it, we need SEEM version that is easily installable.

**Comment by SkalskiP** [comment]
The `maestro` project has pivoted in the direction of a VLM fine-tuning toolkit. As a result, I am closing legacy issues.
