### ISSUE TITLE
refine_marks

### ISSUE THREAD

**Issue by raghudeepika** [roboflow/multimodal-maestro#27]
### Search before asking

- [X] I have searched the Multimodal Maestro [issues](https://github.com/roboflow/multimodal-maestro/issues) and found no similar feature requests.

### Description

Thanks for creating this amazing package! The refine function is not very helpful in most instances. It would be highly beneficial to prompt gpt with the marks of the smaller masks within larger ones and also visualize and extract them. Is it possible to bypass refine_marks?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
The `maestro` project has pivoted in the direction of a VLM fine-tuning toolkit. As a result, I am closing legacy issues.
