### ISSUE TITLE
Error: The model `gpt-4-vision-preview` has been deprecated

### ISSUE THREAD

**Issue by kvnptl** [roboflow/multimodal-maestro#30]
### Search before asking

- [X] I have searched the Multimodal Maestro [issues](https://github.com/roboflow/multimodal-maestro/issues) and found no similar bug report.

### Bug

ValueError: The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations

### Environment

- Google colab

### Minimal Reproducible Example

Run the colab notebook named "multimodal_maestro_gpt_4_vision.ipynb"

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Wheelspawn** [comment]
`gpt-4-vision-preview` is definitely deprecated.
https://platform.openai.com/docs/deprecations/2024-06-06-gpt-4-32k-and-vision-preview-models

I was able to fix this by simply replacing `gpt-4-vision-preview` with `gpt-4o` in `maestro/lmms/gpt4.py`. Fortunately the notebook worked without any further modification.

I've submitted a [PR](https://github.com/roboflow/multimodal-maestro/pull/37) with the change. In the meantime, you can just go to wherever you have the package installed and modify `gpt4.py` to use `gpt-4o`.
