### ISSUE TITLE
WARNING cannot import recipe for Florence 2

### ISSUE THREAD

**Issue by cvmilesight** [roboflow/multimodal-maestro#40]
### Search before asking

- [X] I have searched the Multimodal Maestro [issues](https://github.com/roboflow/multimodal-maestro/issues) and found no similar feature requests.

### Question

maestro --help
🚧 WARNING cannot import recipe for Florence 2

### Additional

Name: maestro
Version: 0.2.0rc3

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS

Python 3.11.5

**Comment by SkalskiP** [comment]
Hi @cvmilesight 👋🏻 what if you do `maestro florence2 --help`?

**Comment by cvmilesight** [comment]
@SkalskiP Maybe there is something wrong with my python environment, I use conda in python 3.10 is OK. Please ignore the problem.

**Comment by SkalskiP** [comment]
Nevertheless, I would like to know what happened. If you had this problem, maybe other users will have it too.
