### ISSUE TITLE
Does multimodal-maestro support Distributed Data Parallel (DDP) training?

### ISSUE THREAD

**Issue by David-19940718** [roboflow/multimodal-maestro#42]
### Search before asking

- [X] I have searched the Multimodal Maestro [issues](https://github.com/roboflow/multimodal-maestro/issues) and found no similar feature requests.

### Description
I'm interested in using maestro for a project that requires distributed training across multiple GPUs. I'd like to know if the project currently supports Distributed Data Parallel (DDP) training, which is a common approach for scaling deep learning models.

### Questions
1. Does maestro currently support DDP training?
2. If yes, is there any documentation or examples showing how to set up and use DDP with this project?
3. If no, are there any plans to implement DDP support in the future?

### Additional Context
DDP training can significantly speed up the training process for large models or datasets by utilizing multiple GPUs efficiently. It would be a valuable feature for users working with resource-intensive multimodal models.

### Environment
- Operating System: Ubuntu 20.04
- Python version: 3.10
- CUDA version (if applicable): 12.1
- GPU model: NVIDIA RTX 3090

Thank you for your time and consideration!

**Comment by David-19940718** [comment]
I’ve encountered another question. :(

When training Florence2 with the default settings, the process appears to proceed without any issues. However, upon completing the training phase, the output generated_text is unexpected like that: '</s><s>9 of spades</s>'. 

Could this be a bug in the framework, or is it possible that the model did not converge properly?

**Comment by David-19940718** [comment]
![image](https://github.com/user-attachments/assets/8bbde4ed-e670-4e38-a89a-8c7aa9f79732)

**Comment by SkalskiP** [comment]
Hi @David-19940718 👋🏻 

W chwili obecnej `maestro` nie wspiera jeszcze DDP ale jak najbardziej mamy plany dodać takie wsparcie i to w niedalekiej przyszłości.

As for the `</s><s>9 of spades</s>` output format. This is expected. The Florence-2 model adds this on its own. You need to remove those extra tags in postporcessing.

**Comment by David-19940718** [comment]
Thank you for your helpful response, @SkalskiP.

Regarding DDP support, I appreciate the update that there are plans to add this capability in the near future. That's great news and will be very useful.

As for the </s><s> tags in the output format, I've actually found that we need to explicitly set certain fields to get the expected results without those extra tags. Specifically, setting the following seems to resolve the issue:

```python
text = "<OD>"
task = "<OD>"
```

This approach appears to prevent the Florence-2 model from adding those tags on its own. However, I'd be interested to hear if you have any insights on why this works or if there's a more ideal way to handle it.

Thanks again for looking into this and providing such a detailed explanation. Your help is much appreciated!
